# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blocked_sample <- function(bsize, nblocks, length) {
    .Call(`_htspop_blocked_sample`, bsize, nblocks, length)
}

.blocked_sums <- function(val, bsize, nblock, rm_na) {
    .Call(`_htspop_blocked_sums`, val, bsize, nblock, rm_na)
}

.blocked_means <- function(val, bsize, nblock, rm_na) {
    .Call(`_htspop_blocked_means`, val, bsize, nblock, rm_na)
}

.blocked_col_sums <- function(matrix, bsize, nblock, rm_na) {
    .Call(`_htspop_blocked_col_sums`, matrix, bsize, nblock, rm_na)
}

.blocked_col_means <- function(matrix, bsize, nblock, rm_na) {
    .Call(`_htspop_blocked_col_means`, matrix, bsize, nblock, rm_na)
}

.bootstrap_col_rates <- function(num, den, nboots, rm_na = FALSE) {
    .Call(`_htspop_bootstrap_col_rates`, num, den, nboots, rm_na)
}

.bootstrap_col_means <- function(val, nboots, rm_na = TRUE) {
    .Call(`_htspop_bootstrap_col_means`, val, nboots, rm_na)
}

.fst_reich <- function(fq, ht, n) {
    .Call(`_htspop_fst_reich`, fq, ht, n)
}

.pairwise_fst_reich <- function(count, n) {
    .Call(`_htspop_pairwise_fst_reich`, count, n)
}

.fst_weir_cockerham <- function(fq, n) {
    .Call(`_htspop_fst_weir_cockerham`, fq, n)
}

.pairwise_fst_weir_cockerham <- function(count, n) {
    .Call(`_htspop_pairwise_fst_weir_cockerham`, count, n)
}

.fst_hudson <- function(fq, n) {
    .Call(`_htspop_fst_hudson`, fq, n)
}

.pairwise_fst_hudson <- function(count, n) {
    .Call(`_htspop_pairwise_fst_hudson`, count, n)
}

.fst_wright <- function(fq) {
    .Call(`_htspop_fst_wright`, fq)
}

.pairwise_fst_wright <- function(count, total) {
    .Call(`_htspop_pairwise_fst_wright`, count, total)
}

.nei_matrix <- function(f) {
    .Call(`_htspop_nei_matrix`, f)
}

.nei <- function(f) {
    .Call(`_htspop_nei`, f)
}

.nei_da_matrix <- function(f) {
    .Call(`_htspop_nei_da_matrix`, f)
}

.nei_da <- function(f) {
    .Call(`_htspop_nei_da`, f)
}

.fast_nei <- function(f) {
    .Call(`_htspop_fast_nei`, f)
}

.bootstrap_fast_nei <- function(f, boots, block) {
    .Call(`_htspop_bootstrap_fast_nei`, f, boots, block)
}

.bootstrap_nei <- function(jxy, jx, block, boots) {
    .Call(`_htspop_bootstrap_nei`, jxy, jx, block, boots)
}

